### ISSUE TITLE
Exclude field from bumping?

### ISSUE THREAD

**Issue by Slapbox** [stevelacy/gulp-bump#78]
Gulp-Bump has been an amazing help. I just tried to wire it up to a new `json` file that has a `version` property,  but it also has an `sdkVersion` property. The `sdkVersion` property gets bumped along with the `version`. 

Can this be prevented? I looked at the docs and saw some ways I thought might work, but I've had no luck.

**Comment by stevelacy** [comment]
It will not bump a second key by default, you must provide an array of keys for it to bump.
Your issue is `sdkVersion` is probably above the `version` key, causing it to be bumped before the parser finds the `version` key.
Use a custom regex to remove any filler values ahead of the `version`, or set `case: true` to ignore all capital letters.

**Comment by stevelacy** [comment]
https://github.com/stevelacy/gulp-bump/commit/5b68f68e705381964cc0f3ea2b64ce1672ce8f32

**Comment by Slapbox** [comment]
Jeez all I had to do was move the key property up in the file? Fantastic!

Thanks so much for your help!
